// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ApplicationFormController from "controllers/application_form_controller"
application.register("application-form", ApplicationFormController)

import AuthTabsController from "controllers/auth_tabs_controller"
application.register("auth-tabs", AuthTabsController)

import BadgeAwardController from "controllers/badge_award_controller"
application.register("badge-award", BadgeAwardController)

import ChallengeFormController from "controllers/challenge_form_controller"
application.register("challenge-form", ChallengeFormController)

import CostTypeController from "controllers/cost_type_controller"
application.register("cost-type", CostTypeController)

import FlashController from "controllers/flash_controller"
application.register("flash", FlashController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ModalController from "controllers/modal_controller"
application.register("modal", ModalController)

import RatingController from "controllers/rating_controller"
application.register("rating", RatingController)

import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)

import ThresholdInputController from "controllers/threshold_input_controller"
application.register("threshold-input", ThresholdInputController)

import ChallengeSettingsController from "controllers/challenge_settings_controller"
application.register("challenge-settings", ChallengeSettingsController)

import ScrollNavController from "controllers/scroll_nav_controller"
application.register("scroll-nav", ScrollNavController)

import GatheringFormController from "controllers/gathering_form_controller"
application.register("gathering-form", GatheringFormController)

import ToggleListController from "controllers/toggle_list_controller"
application.register("toggle-list", ToggleListController)

import PwaBannerController from "controllers/pwa_banner_controller"
application.register("pwa-banner", PwaBannerController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)
