// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationFormController from "./application_form_controller"
application.register("application-form", ApplicationFormController)

import AuthTabsController from "./auth_tabs_controller"
application.register("auth-tabs", AuthTabsController)

import BadgeAwardController from "./badge_award_controller"
application.register("badge-award", BadgeAwardController)

import ChallengeFormController from "./challenge_form_controller"
application.register("challenge-form", ChallengeFormController)

import ChallengeSettingsController from "./challenge_settings_controller"
application.register("challenge-settings", ChallengeSettingsController)

import CostTypeController from "./cost_type_controller"
application.register("cost-type", CostTypeController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThresholdInputController from "./threshold_input_controller"
application.register("threshold-input", ThresholdInputController)
